Trap elv use ca ncoder
frc6377/crescendo_2024 pull request #101
Opened 2024-01-31 03:33 UTC by ModBoyex

## Justification

## Implementaion

## Testing Done

2024-01-31 22:08 UTC, azvanderpas requested changes

2024-01-31 22:08 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/TrapElvSubsystem.java
> +              0);
Gravity for this physics model points in the -90 degree direction. 

For the mechanism, however, down is 180 degrees. 

Should be able to make those agree by adding offsets in the right places.

2024-01-31 23:30 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/TrapElvSubsystem.java
> +  }
Append .withName(...) to the returned Commands so we can track them in logs

2024-02-03 17:09 UTC, riversry approved these changes

2024-02-03 17:12 UTC, azvanderpas approved these changes

2024-02-03 17:12 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/TrapElvSubsystem.java
> +    wristMech.setAngle(Units.radiansToDegrees(m_wristMotorSim.getAngleRads()) - 90);
Add comment about why the 90 degree offset is necessary.

2024-02-03 20:04 UTC, azvanderpas approved these changes

2024-02-03 20:24 UTC, merged