Feature/assisted steering
frc6377/crescendo_2024 pull request #200
Opened 2024-03-07 01:39 UTC by KianChilds

## Justification
Makes steering simpler

## Implementaion
A button that activates auto rotation. Using inference to determine which target to rotate to.

## Testing Done
as of 3/6/24 none

2024-03-07 01:55 UTC, KianChilds commented
fixes issue #195

2024-03-08 01:24 UTC, azvanderpas requested changes

2024-03-08 01:24 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +  }
Seem like these fit in FieldConstants. Also can't leave null, of course

2024-03-08 01:24 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/swerveSubsystem/SwerveCommandFactory.java
> +    return () -> subsystem.getState().Pose.getX() > FieldConstants.CENTERLINE_X;
Isn't this alliance color dependent as well?

2024-03-08 01:24 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/swerveSubsystem/SwerveCommandFactory.java
> +        .asProxy();
Add withNames

2024-03-08 01:24 UTC, azvanderpas commented on src/main/java/frc/robot/Constants.java
> +    public static final double CENTERLINE_X = 0;
Is this a TODO number?

2024-03-10 00:33 UTC, lohengrin332 commented on src/main/java/frc/robot/Robot.java
> +    if (DriverStation.getAlliance().get() == Alliance.Red) {
A comment might be nice here. E.g.:

```suggestion
    // BLUE is the default, so we only need to handle RED here.
    if (DriverStation.getAlliance().get() == Alliance.Red) {
```

2024-03-10 00:35 UTC, lohengrin332 commented on src/main/java/frc/robot/RobotContainer.java
> +    // new Trigger(trapElvCommandFactory.getSourceBreak())
Per our conversation, please un-comment this block.

2024-03-10 00:35 UTC, lohengrin332 commented on src/main/java/frc/robot/RobotContainer.java
> +    // return Commands.parallel(
Please also uncomment this block.

2024-03-10 00:36 UTC, lohengrin332 commented on src/main/java/frc/robot/RobotContainer.java
> +        // .until(trapElvCommandFactory.getSourceBreak())
Please also uncomment this block.

2024-03-10 00:37 UTC, lohengrin332 commented on src/main/java/frc/robot/subsystems/swerveSubsystem/SwerveCommandFactory.java
> +    BooleanSupplier onNearSide = isOnNearSide(() -> RSM.getAllianceColor() == AllianceColor.RED);
These should be made final.

2024-03-10 00:45 UTC, lohengrin332 approved these changes
LGTM

2024-03-10 00:48 UTC, lohengrin332 approved these changes

2024-03-10 00:49 UTC, merged