Debug log pose/size
frc6377/crescendo_2024 pull request #207
Opened 2024-03-09 22:22 UTC by ModBoyex

## Justification

## Implementaion

## Testing Done

2024-03-10 16:31 UTC, caseyjbrotherton requested changes

2024-03-10 16:31 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/trapElvSubsystem/TrapElvSubsystem.java
> +  private DebugEntry<Double> WristPositionEntry;
Nit:  wristPositionEntry

2024-03-10 16:31 UTC, caseyjbrotherton commented on src/main/java/frc/robot/subsystems/trapElvSubsystem/TrapElvSubsystem.java
> +  private DebugEntry<String> WristStateEntry;
wristStateEntry

2024-03-10 16:41 UTC, azvanderpas commented on src/main/java/frc/robot/utilities/DebugEntry.java
> +    localConsumer.accept(defaultValue);
This is why the check is failing. Needs to happen whether or not we are in competition mode, but skipped if the localEntry is null (i.e. wrong type was used)

2024-03-14 01:02 UTC, azvanderpas approved these changes

2024-03-14 01:13 UTC, caseyjbrotherton approved these changes

2024-03-14 01:13 UTC, merged