re add wirst scoring auto command + TOF Tweaks
frc6377/crescendo_2024 pull request #213
Opened 2024-03-10 19:15 UTC by ModBoyex

## Justification

The command for scoring Amp in auto was commented out. this pull request re-implements it and adds the TOF as a factor in running the rollers.

## Testing Done

This still needs to be tested, but might be able to be tested at Westlake

2024-03-14 00:45 UTC, azvanderpas requested changes

2024-03-14 00:45 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
> +        Commands.waitUntil(trapElvSubsystem.isAMPReady())
If this subsystem is disabled, this will cause a crash

2024-03-14 00:45 UTC, azvanderpas commented on src/main/java/frc/robot/RobotContainer.java
> +    if (enabledSubsystems.shooterEnabled) {
Shouldn't need this if we setup our command factories correctly.
Same with other subsystem enabled checks in this method

2024-03-14 00:45 UTC, azvanderpas commented on src/main/java/frc/robot/subsystems/trapElvSubsystem/TrapElvCommandFactory.java
> +        .runEnd(
This should still work with startEnd, right?

2024-03-29 01:08 UTC, caseyjbrotherton approved these changes

2024-03-29 01:08 UTC, merged